[package]
name = "neptune"
description = "Poseidon hashing over BLS12-381 for Filecoin."
version = "10.0.0"
authors = ["porcuquine <porcuquine@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lurk-lab/neptune"
resolver = "2"
rust-version = "1.62.1"

[dependencies]
bellperson = { version = "0.25", default-features = false }
blake2s_simd = "0.5"
blstrs = { version = "0.7.0", optional = true }
byteorder = "1"
ec-gpu = { version = "0.2.0", optional = true }
ec-gpu-gen = { version = "0.6.0", optional = true }
ff = "0.13.0"
generic-array = "0.14.6"
itertools = { version = "0.8.2" }
log = "0.4.17"
pasta_curves = { version = "0.5", features = ["serde"] }
trait-set = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
abomonation = "0.7.3"
abomonation_derive = { git = "https://github.com/winston-h-zhang/abomonation_derive.git" }

[dev-dependencies]
bincode = "1.3.3"
blstrs = "0.7.0"
criterion = "0.4.0"
rand = "0.8.5"
rand_xorshift = "0.3.0"
serde_json = "1.0.94"
sha2 = "0.9"

[build-dependencies]
blstrs = "0.7.0"
ec-gpu = { version = "0.2.0", optional = true }
ec-gpu-gen = { version = "0.6.0", optional = true }
pasta_curves = { version = "0.5", features = ["serde"] }

[[bench]]
name = "hash"
harness = false

[[bench]]
name = "synthesis"
harness = false

[profile.bench]
incremental = false
codegen-units = 1

[features]
default = ["bellperson/default"]
cuda = ["ec-gpu-gen/cuda", "ec-gpu", "pasta_curves/gpu"]
opencl = ["ec-gpu-gen/opencl", "ec-gpu", "pasta_curves/gpu"]
# The supported arities for Poseidon running on the GPU are specified at compile-time.
arity2 = []
arity4 = []
arity8 = []
arity11 = []
arity16 = []
arity24 = []
arity36 = []
# With this feature set, also the strengthened version of the kernel will be compiled.
strengthened = []
# The supported fields for Poseidon running on the GPU are specified at compile-time.
bls = ["blstrs/gpu"]
pasta = ["pasta_curves/gpu"]

[workspace]
members = [
  "gbench",
]
