[package]
name = "gbench"
description = "GPU benchmark program for Neptune"
version = "0.5.4"
authors = ["porcuquine <porcuquine@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4.0"
bellperson = "0.6.3"
blake2s_simd = "0.5"
byteorder = "1"
env_logger = "0.7.1"
ff = { version = "0.2.1", package = "fff" }
generic-array = "0.13.2"
log = "0.4.8"
paired = "0.20.0"
neptune = { path = "../", features=["gpu"] }
