[package]
name = "gbench"
description = "GPU benchmark program for Neptune"
version = "0.5.4"
authors = ["porcuquine <porcuquine@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4.0"
bellperson = { git = "https://github.com/filecoin-project/bellperson", branch = "master" }
blake2s_simd = "0.5"
byteorder = "1"
env_logger = "0.7.1"
ff = "0.11.0"
generic-array = "0.14.4"
log = "0.4.8"
neptune = { path = "../", default-features = false }
rust-gpu-tools = { git = "https://github.com/filecoin-project/rust-gpu-tools", branch = "master", default-features = false, optional = true }
structopt = { version = "0.3", default-features = false }
blstrs = { git = "https://github.com/filecoin-project/blstrs", branch = "master" }

[features]
default = ["futhark"]
cuda = ["neptune/cuda", "rust-gpu-tools/cuda"]
futhark = ["neptune/futhark", "rust-gpu-tools/opencl"]
opencl = ["neptune/opencl", "rust-gpu-tools/opencl"]
