[package]
name = "gbench"
description = "GPU benchmark program for Neptune"
version = "0.5.4"
authors = ["porcuquine <porcuquine@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4.0"
bellperson = { version = "0.12", default-features = false }
blake2s_simd = "0.5"
byteorder = "1"
env_logger = "0.7.1"
ff = { version = "0.2.1", package = "fff" }
generic-array = "0.14.4"
log = "0.4.8"
neptune = { path = "../", default-features = false }
rust-gpu-tools = { version = "0.3.0", optional = true }
structopt = { version = "0.3", default-features = false }

[features]
default = ["pairing", "gpu"]
gpu = ["neptune/gpu", "rust-gpu-tools"]
opencl = ["neptune/opencl", "rust-gpu-tools"]
pairing = ["neptune/pairing", "bellperson/pairing"]
blst = ["neptune/blst", "bellperson/blst"]
